### PR TITLE
Approach to `var` statements in ES5

### PR DESCRIPTION
**Pull request by chris-kobrzak**
We have a different approach to multiple `var` statements and this is what's covered in this PR.

### CODE REVIEW

**Comment by cobacious** [comment]
Normally I would have agreed with this without question, but then I read this article... :confused: 
http://benalman.com/news/2012/05/multiple-var-statements-javascript/

**Comment by chris-kobrzak** [comment]
Good call but per as our recent conversation, I would still say the DRY argument still outweighs all the points Ben raised in his article.
- As for the maintenance, it's hard not to have an impression this is pure laziness :-) I can't take it seriously when the guy is saying a few more mouse clicks when re-ordering lines of text should be an argument in favour of anything.
- The ASI stuff - I'm pretty sure JSHint would highlight a syntax issue if you forgot to include a comma or mistakenly put a semicolon at the end of the line.
- As for the indentation, I normally use two spaces and indeed, this doesn't look particularly pretty.  But does it really need to?  As Uncle Bob preaches in his epic "Clean Code" ~~bible~~ _book_, you are supposed to read code by rows, not columns so this doesn't really matter, IMHO.
- If you end up with a need to have multiple multi-line expressions, you probably have a bigger fish to fry and your code needs some simplification and re-factoring!
- I agree with those arguing that comments are nothing more but a code smell.  If you need to put comments in your code, it usually indicates it hasn't been written in the most comprehensive way.  In this case just rename your variables to something meaningful and you won't need any comments (so it's not really relevant to the main issue of var-ing or not var-ing).

**Comment by cobacious** [comment]
I agree. Always good to question these things though :smile:

**Comment by chris-kobrzak** [comment]
Absolutely, cheers for merging!

**Pull request merged**
